FollowerProtocol: followerFinal.o pca9685/pca9685.c -lwiringPi
	gcc -o FollowerProtocol followerFinal.c pca9685/pca9685.c -lwiringPi

followerFinal.o: followerFinal.c pca9685/pca9685.c -lwiringPi
	gcc -g -c followerFinal.c  pca9685/pca9685.c -lwiringPi
